### ISSUE TITLE
蜜汁错误 明明是list of tuple为什么变成int了

### ISSUE THREAD

**Issue by zhengfeitian** [zhengfeitian/esbc#8]
2018-06-22 18:13:08 ERROR Executor:91 - Exception in task 0.0 in stage 31.0 (TID 30)
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/home/pc/spark/python/lib/pyspark.zip/pyspark/worker.py", line 230, in main
    process()
  File "/home/pc/spark/python/lib/pyspark.zip/pyspark/worker.py", line 225, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/home/pc/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 372, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/home/pc/spark/python/pyspark/rdd.py", line 860, in func
    yield reduce(f, iterator, initial)
  File "/home/pc/spark/python/pyspark/util.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "<stdin>", line 6, in reducer1
TypeError: 'int' object has no attribute '__getitem__'

**Comment by zhengfeitian** [comment]
因为reduce前后的状态改变了  有的item reduce之后类型不匹配
